## global
seed: 31
device: cuda
mode: train
best_path: None 
debug: False  

## data 
data_dir: data
dataset: Haikou
input_length: 16
batch_size: 32
test_batch_size: 32
graph_file: data/Haikou/out/adj_layer4.csv
IO: out
isweighted: noweighted

## model 
d_input: 1                 # means inflow and outflow
d_output: 4                 # means inflow and outflow
d_model: 64
dropout: 0.2
percent: 0.1                # augumentation percentage  
shm_temp: 0.5               # temperature for loss of spatial heterogeneity modeling  , 0.5 is best for NYCBike
nmb_prototype: 6            # number of cluster 
yita: 0.6                   # balance for inflow loss and outflow loss, $yita * inflow + (1 - yita) * outflow$

## train
epochs: 100
lr_init: 0.01
early_stop: False
early_stop_patience: 15
grad_norm: True
max_grad_norm: 5
use_dwa: True         # whether to use dwa for loss balance
temp: 4               # tempurature parameter in dwa, a larger T means more similer weights
