name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
    build:
      runs-on: ${{ matrix.os }}
        
      strategy:
        matrix:
          os: [ubuntu-20.04]

      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7.17
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          python-version: 3.7
      - run: conda --version
      - run: which python
      - name: Install main dependencies
        run: |
         python -m pip install torch==1.10.1+cpu torchvision==0.11.2+cpu torchaudio==0.10.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
         python -m pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cpu.html
         python -m pip install torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cpu.html
         python -m pip install torch-geometric
         python -m pip install sphinx sphinx_rtd_theme
      - name: Install main package
        run: |
          python -m pip install -e .[test]
      - name: Run test-suite
        run: |
          python -m pytest
      - name: Generate coverage report
        if: success()
        run: |
          pip install coverage
          coverage run -m pytest
          coverage xml
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v1
        if: success()
        with:
          file: coverage.xml
